### ISSUE TITLE
SyntaxError ... but not?

### ISSUE THREAD

**Issue by cviebrock** [gersongoulart/gulp-swagger#1]
First, this plug in is exactly what I need ... thanks!

Previously, I was using the `swagger-cli` tool to validate and compile my sources, which works fine:

``` sh
$ ./node_modules/.bin/swagger bundle -o resources/documentation/api/v1/swagger.json resources/documentation/api/v1/swagger.yaml
Created resources/documentation/api/v1/swagger.json from resources/documentation/api/v1/swagger.yaml
```

I tried to make this part of my gulp build with the following:

``` js
gulp.task('swagger', function () {
    gulp.src('./resources/documentation/api/v1/swagger.yaml')
        .pipe(swagger('swagger.json'))
        .pipe(gulp.dest('./resources/documentation/api/v1'));
});
```

But now running `gulp swagger`, I get syntax errors:

``` sh
$ gulp swagger
[11:02:19] Using gulpfile ~/Documents/workspace/my_site/gulpfile.js
[11:02:19] Starting 'swagger'...
[11:02:19] Finished 'swagger' after 7.41 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Error in Swagger definition 
Error: Error opening file "/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/ReviewImages.yaml" 
Error: ENOENT, open '/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/ReviewImages.yaml'
    at makeError (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:314:16)
    at Object.module.exports.newSyntaxError (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:84:14)
    at errBack (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/parse.js:87:14)
    at /Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/parse.js:60:7
    at crawlNextProperty (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:262:9)
    at /Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:281:13
    at Immediate.invokeCallback [as _onImmediate] (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:53:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17) 

Error: Error opening file "/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/ReviewImages.yaml" 
Error: ENOENT, open '/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/ReviewImages.yaml'
    at makeError (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:314:16)
    at Object.module.exports.newError (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/util.js:67:14)
    at errorHandler (/Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/read.js:46:19)
    at /Users/admin/Documents/workspace/my_site/node_modules/gulp-swagger/node_modules/swagger-parser/lib/read.js:58:16
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15) 

Error: ENOENT, open '/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/ReviewImages.yaml'
    at Error (native)
```

Any suggestions?  Doing it the "old" way generates the .json I was expecting, without any errors.

Thanks!

**Comment by gersongoulart** [comment]
@cviebrock: Sorry for the long hiatus. It almost looks like it's trying to load `ReviewImages.yaml` from the wrong directory? Would you mind pasting here the line of code (inside `swagger.yaml`) that contains the `$ref` to `ReviewImages.yaml`?

Meantime I need to do some work to update the dependencies anyways so might as well try to reproduce and fix this problem...

**Comment by cviebrock** [comment]
@gersongoulart: No worries about the hiatus!

I've moved on in the project since posting my issue, so my swagger.yaml file is different.  I still get the same error, but with a different model now:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Error in Swagger definition 
Error: Error opening file "/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml" 
Error: ENOENT, open '/Users/admin/Documents/workspace/my_site/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml'
```

My directory is structured like this:

```
swagger.yaml
refs/
    definitions.yaml
    definitions/
        UserWithProfileImageAndRating.yaml
        OtherStuff.yaml
```

`/refs/definitions.yaml` is basically a list of defs with their refs:

``` yaml
UserWithProfileImage:
  $ref: "definitions/UserWithProfileImage.yaml"

UserWithProfileImageAndRating:
  $ref: "definitions/UserWithProfileImageAndRating.yaml"
```

Note that those $refs are relative to the location of the definitions.yaml file.  It looks like gulp-swagger is reading those in, and assuming they are relative to the base directory of the swagger.yaml file.

Anything else I can paste that might be helpful for you?

**Comment by richard-reedy-volusion** [comment]
I think I'm having a similiar problem.  I'm referencing an external file and when I run swagger build, the file has a "null" in the result.  i was able to get this working by changing dereference$Refs option in swagger-parser to true in the gulp-swagger/index.js file.  I'm not sure if this is the right solution, but its working.

index.js

```
dereference$Refs: true
```

My swagger.yaml 

```
...
 $ref: ./definitions_m/ViewModelsCommonPaymentKey.yaml
...
```

**Comment by gersongoulart** [comment]
@cviebrock, @richard-reedy-volusion I just merged the PR.
@cviebrock: Please let me know if that works for you as well...

This project needs some refactoring but I'm busy at the time... Looking more closely into it is one of my resolutions for 2016! :)

**Comment by richard-reedy-volusion** [comment]
@gersongoulart  Just noticed that npm still has the old version.  When you get a chance could you publish the update?

**Comment by gersongoulart** [comment]
Done :)

**Comment by cviebrock** [comment]
Sorry for finally giving feedback on this.  I seem to still have the same error:

```
$ gulp swagger
[13:37:19] Using gulpfile ~/Documents/workspace/my-app/gulpfile.js
[13:37:19] Starting 'swagger'...
[13:37:19] Finished 'swagger' after 12 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Error in Swagger definition 
Error: Error opening file "/Users/admin/Documents/workspace/my-app/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml" 
Error: ENOENT, open '/Users/admin/Documents/workspace/my-app/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml'
    at makeError (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:314:16)
    at Object.module.exports.newSyntaxError (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:84:14)
    at errBack (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/parse.js:87:14)
    at /Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/parse.js:60:7
    at crawlNextProperty (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:262:9)
    at /Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:281:13
    at Immediate.invokeCallback [as _onImmediate] (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:53:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17) 

Error: Error opening file "/Users/admin/Documents/workspace/my-app/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml" 
Error: ENOENT, open '/Users/admin/Documents/workspace/my-app/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml'
    at makeError (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:314:16)
    at Object.module.exports.newError (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/util.js:67:14)
    at errorHandler (/Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/read.js:46:19)
    at /Users/admin/Documents/workspace/my-app/node_modules/swagger-parser/lib/read.js:58:16
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15) 

Error: ENOENT, open '/Users/admin/Documents/workspace/my-app/resources/documentation/api/v1/definitions/UserWithProfileImageAndRating.yaml'
    at Error (native)
```

**Comment by richard-reedy-volusion** [comment]
My folder structure is similiar to yours with one exception.  I dont have a master defintions.yaml that contains all my defintions.  I'm referencing the individual yaml files within the folder using

$ref: "./definitions_m/ViewModelsCommonPaymentKey.yaml"

**Comment by gersongoulart** [comment]
@cviebrock, @richard-reedy-volusion: In fact a schema split into multiple files was still failing. I believe I managed to fix the problem with v0.0.10. Would you be kind to test and let me know if the solution works for you guys? I'll reopen this issue until I have your feedback that we're good to close.

**Comment by cviebrock** [comment]
V0.0.10 works for me ... thanks!  I guess the only option now is to dereference all my $refs, right?

**Comment by gersongoulart** [comment]
That's good to hear! What do you mean by "the only option now is to dereference all my $refs"?

**Comment by cviebrock** [comment]
Here is a sample of my YAML spec:

``` yaml
"/jobs/{jobId}":
  get:
    summary: Get a job
    description: Get the details for one of the current user's jobs.
    operationId: getJob
    tags:
      - Jobs
    security:
      - jwt: []
    parameters:
      - $ref: "#/parameters/JobId"
    responses:
      "200":
        description: Success
        schema:
          type: object
          properties:
            data:
              $ref: "#/definitions/JobWithImagesAndTasks"
      "403":
        $ref: "#/responses/notAuthorized"
      "404":
        $ref: "#/responses/notFound"
      "422":
        $ref: "#/responses/validationError"
```

When I use the CLI swagger tool to bundle this:

``` sh
./node_modules/.bin/swagger bundle -o resources/documentation/api/v1/swagger.json resources/documentation/api/v1/swagger.yaml
```

... the resulting JSON looks like:

``` json
"/jobs/{jobId}": {
  "get": {
    "summary": "Get a job",
    "description": "Get the details for one of the current user's jobs.",
    "operationId": "getJob",
    "tags": [
      "Jobs"
    ],
    "security": [
      {
        "jwt": []
      }
    ],
    "parameters": [
      {
        "$ref": "#/parameters/JobId"
      }
    ],
    "responses": {
      "200": {
        "description": "Success",
        "schema": {
          "type": "object",
          "properties": {
            "data": {
              "$ref": "#/definitions/JobWithImagesAndTasks"
            }
          }
        }
      },
      "403": {
        "$ref": "#/responses/notAuthorized"
      },
      "404": {
        "$ref": "#/responses/notFound"
      },
      "422": {
        "$ref": "#/responses/validationError"
      }
    }
  }
}
```

Using gulp-swagger, all those `$ref`s are dereferenced, and I end up with:

``` json

"/jobs/{jobId}": {
  "get": {
    "summary": "Get a job",
    "description": "Get the details for one of the current user's jobs.",
    "operationId": "getJob",
    "tags": [
      "Jobs"
    ],
    "security": [
      {
        "jwt": []
      }
    ],
    "parameters": [
      {
        "name": "jobId",
        "description": "The identifier for the job",
        "in": "path",
        "required": true,
        "type": "integer"
      }
    ],
    "responses": {
      "200": {
        "description": "Success",
        "schema": {
          "type": "object",
          "properties": {
            "data": {
              "description": "A complete job object",
              "type": "object",
              "allOf": [
                {
                  "description": "Job identifier",
                  "type": "object",
                  "required": [
                    "jobId"
                  ],
                  "properties": {
                    "jobId": {
                      "description": "Identifier for the job",
                      "type": "integer"
                    }
                  }
                },
                {
                  "description": "Base information about a job",
                  "type": "object",
                  "required": [
                    "name",
                    "description",
                    "status",
                    "consumer",
                    "provider"
                  ],
                  "properties": {
                    "name": {
                      "description": "The name of the job",
                      "type": "string",
                      "example": "After-party Cleanup"
                    },
...
```

Is there a way to keep the output from dereferencing everything (i.e. parameters, definitions and responses)?

**Comment by gersongoulart** [comment]
Need to do some investigation... PR welcome if you manage to get to it first! :P
